nickname = {
    'Air Force': 'Falcons',
    'Akron': 'Zips',
    'Alabama': 'Crimson Tide',
    'Appalachian State': 'Mountaineers',
    'Arizona': 'Wildcats',
    'Arizona State': 'Sun Devils',
    'Arkansas': 'Razorbacks',
    'Arkansas State': 'Red Wolves',
    'Army': 'Black Knights',
    'Auburn': 'Tigers',
    'Ball State': 'Cardinals',
    'Baylor': 'Bears',
    'Boise State': 'Broncos',
    'Boston College': 'Eagles',
    'Bowling Green': 'Falcons',
    'Buffalo': 'Bulls',
    'BYU': 'Cougars',
    'California': 'Golden Bears',
    'Central Michigan': 'Chippewas',
    'Charlotte': '49ers',
    'Cincinnati': 'Bearcats',
    'Clemson': 'Tigers',
    'Coastal Carolina': 'Chanticleers',
    'Colorado': 'Buffaloes',
    'Colorado State': 'Rams',
    'Duke': 'Blue Devils',
    'East Carolina': 'Pirates',
    'Eastern Michigan': 'Eagles',
    'FIU': 'Panthers',
    'Florida': 'Gators',
    'Florida Atlantic': 'Owls',
    'Florida State': 'Seminoles',
    'Fresno State': 'Bulldogs',
    'Georgia': 'Bulldogs',
    'Georgia Southern': 'Eagles',
    'Georgia State': 'Panthers',
    'Georgia Tech': 'Yellow Jackets',
    'Hawaii': 'Rainbow Warriors',
    'Houston': 'Cougars',
    'Illinois': 'Fighting Illini',
    'Indiana': 'Hoosiers',
    'Iowa': 'Hawkeyes',
    'Iowa State': 'Cyclones',
    'James Madison': 'Dukes',
    'Kansas': 'Jayhawks',
    'Kansas State': 'Wildcats',
    'Kent State': 'Golden Flashes',
    'Kentucky': 'Wildcats',
    'Liberty': 'Flames',
    'Louisiana': "Ragin' Cajuns",
    'Louisiana Tech': 'Bulldogs',
    'Louisiana-Monroe': 'Warhawks',
    'Louisville': 'Cardinals',
    'LSU': 'Tigers',
    'Marshall': 'Thundering Herd',
    'Maryland': 'Terrapins',
    'Memphis': 'Tigers',
    'Miami (FL)': 'Hurricanes',
    'Miami (OH)': 'RedHawks',
    'Michigan': 'Wolverines',
    'Michigan State': 'Spartans',
    'Middle Tennessee': 'Blue Raiders',
    'Minnesota': 'Golden Gophers',
    'Mississippi State': 'Bulldogs',
    'Missouri': 'Tigers',
    'Navy': 'Midshipmen',
    'NC State': 'Wolfpack',
    'Nebraska': 'Cornhuskers',
    'Nevada': 'Wolf Pack',
    'New Mexico': 'Lobos',
    'New Mexico State': 'Aggies',
    'North Carolina': 'Tar Heels',
    'North Texas': 'Mean Green',
    'Northern Illinois': 'Huskies',
    'Northwestern': 'Wildcats',
    'Notre Dame': 'Fighting Irish',
    'Ohio': 'Bobcats',
    'Ohio State': 'Buckeyes',
    'Oklahoma': 'Sooners',
    'Oklahoma State': 'Cowboys',
    'Old Dominion': 'Monarchs',
    'Ole Miss': 'Rebels',
    'Oregon': 'Ducks',
    'Oregon State': 'Beavers',
    'Penn State': 'Nittany Lions',
    'Pittsburgh': 'Panthers',
    'Purdue': 'Boilermakers',
    'Rice': 'Owls',
    'Rutgers': 'Scarlet Knights',
    'San Diego State': 'Aztecs',
    'San Jose State': 'Spartans',
    'SMU': 'Mustangs',
    'South Alabama': 'Jaguars',
    'South Carolina': 'Gamecocks',
    'South Florida': 'Bulls',
    'Southern Miss': 'Golden Eagles',
    'Stanford': 'Cardinal',
    'Syracuse': 'Orange',
    'TCU': 'Horned Frogs',
    'Temple': 'Owls',
    'Tennessee': 'Volunteers',
    'Texas': 'Longhorns',
    'Texas A&M': 'Aggies',
    'Texas State': 'Bobcats',
    'Texas Tech': 'Red Raiders',
    'Toledo': 'Rockets',
    'Troy': 'Trojans',
    'Tulane': 'Green Wave',
    'Tulsa': 'Golden Hurricane',
    'UAB': 'Blazers',
    'UCF': 'Knights',
    'UCLA': 'Bruins',
    'UConn': 'Huskies',
    'UMass': 'Minutemen',
    'UNLV': 'Rebels',
    'USC': 'Trojans',
    'Utah': 'Utes',
    'Utah State': 'Aggies',
    'UTEP': 'Miners',
    'UTSA': 'Roadrunners',
    'Vanderbilt': 'Commodores',
    'Virginia': 'Cavaliers',
    'Virginia Tech': 'Hokies',
    'Wake Forest': 'Demon Deacons',
    'Washington': 'Huskies',
    'Washington State': 'Cougars',
    'West Virginia': 'Mountaineers',
    'Western Kentucky': 'Hilltoppers',
    'Western Michigan': 'Broncos',
    'Wisconsin': 'Badgers',
    'Wyoming': 'Cowboys',
}

city = {
    'Air Force': 'Colorado Springs',
    'Akron': 'Akron',
    'Alabama': 'Tuscaloosa',
    'Appalachian State': 'Boone',
    'Arizona': 'Tucson',
    'Arizona State': 'Tempe',
    'Arkansas': 'Fayetteville',
    'Arkansas State': 'Jonesboro',
    'Army': 'West Point',
    'Auburn': 'Auburn',
    'Ball State': 'Muncie',
    'Baylor': 'Waco',
    'Boise State': 'Boise',
    'Boston College': 'Chestnut Hill',
    'Bowling Green': 'Bowling Green',
    'Buffalo': 'Buffalo',
    'BYU': 'Provo',
    'California': 'Berkeley',
    'Central Michigan': 'Mount Pleasant',
    'Charlotte': 'Charlotte',
    'Cincinnati': 'Cincinnati',
    'Clemson': 'Clemson',
    'Coastal Carolina': 'Conway',
    'Colorado': 'Boulder',
    'Colorado State': 'Fort Collins',
    'Duke': 'Durham',
    'East Carolina': 'Greenville',
    'Eastern Michigan': 'Ypsilanti',
    'FIU': 'Miami',
    'Florida': 'Gainesville',
    'Florida Atlantic': 'Boca Raton',
    'Florida State': 'Tallahassee',
    'Fresno State': 'Fresno',
    'Georgia': 'Athens',
    'Georgia Southern': 'Statesboro',
    'Georgia State': 'Atlanta',
    'Georgia Tech': 'Atlanta',
    'Hawaii': 'Honolulu',
    'Houston': 'Houston',
    'Illinois': 'Urbana?Champaign',
    'Indiana': 'Bloomington',
    'Iowa': 'Iowa City',
    'Iowa State': 'Ames',
    'James Madison': 'Harrisonburg',
    'Kansas': 'Lawrence',
    'Kansas State': 'Manhattan',
    'Kent State': 'Kent',
    'Kentucky': 'Lexington',
    'Liberty': 'Lynchburg',
    'Louisiana': 'Lafayette',
    'Louisiana Tech': 'Ruston',
    'Louisiana-Monroe': 'Monroe',
    'Louisville': 'Louisville',
    'LSU': 'Baton Rouge',
    'Marshall': 'Huntington',
    'Maryland': 'College Park',
    'Memphis': 'Memphis',
    'Miami (FL)': 'Coral Gables',
    'Miami (OH)': 'Oxford',
    'Michigan': 'Ann Arbor',
    'Michigan State': 'East Lansing',
    'Middle Tennessee': 'Murfreesboro',
    'Minnesota': 'Minneapolis',
    'Mississippi State': 'Starkville',
    'Missouri': 'Columbia',
    'Navy': 'Annapolis',
    'NC State': 'Raleigh',
    'Nebraska': 'Lincoln',
    'Nevada': 'Reno',
    'New Mexico': 'Albuquerque',
    'New Mexico State': 'Las Cruces',
    'North Carolina': 'Chapel Hill',
    'North Texas': 'Denton',
    'Northern Illinois': 'DeKalb',
    'Northwestern': 'Evanston',
    'Notre Dame': 'South Bend',
    'Ohio': 'Athens',
    'Ohio State': 'Columbus',
    'Oklahoma': 'Norman',
    'Oklahoma State': 'Stillwater',
    'Old Dominion': 'Norfolk',
    'Ole Miss': 'Oxford',
    'Oregon': 'Eugene',
    'Oregon State': 'Corvallis',
    'Penn State': 'University Park',
    'Pittsburgh': 'Pittsburgh',
    'Purdue': 'West Lafayette',
    'Rice': 'Houston',
    'Rutgers': 'Piscataway',
    'San Diego State': 'San Diego',
    'San Jose State': 'San Jose',
    'SMU': 'University Park',
    'South Alabama': 'Mobile',
    'South Carolina': 'Columbia',
    'South Florida': 'Tampa',
    'Southern Miss': 'Hattiesburg',
    'Stanford': 'Stanford',
    'Syracuse': 'Syracuse',
    'TCU': 'Fort Worth',
    'Temple': 'Philadelphia',
    'Tennessee': 'Knoxville',
    'Texas': 'Austin',
    'Texas A&M': 'College Station',
    'Texas State': 'San Marcos',
    'Texas Tech': 'Lubbock',
    'Toledo': 'Toledo',
    'Troy': 'Troy',
    'Tulane': 'New Orleans',
    'Tulsa': 'Tulsa',
    'UAB': 'Birmingham',
    'UCF': 'Orlando',
    'UCLA': 'Los Angeles',
    'UConn': 'Storrs',
    'UMass': 'Amherst',
    'UNLV': 'Las Vegas',
    'USC': 'Los Angeles',
    'Utah': 'Salt Lake City',
    'Utah State': 'Logan',
    'UTEP': 'El Paso',
    'UTSA': 'San Antonio',
    'Vanderbilt': 'Nashville',
    'Virginia': 'Charlottesville',
    'Virginia Tech': 'Blacksburg',
    'Wake Forest': 'Winston-Salem',
    'Washington': 'Seattle',
    'Washington State': 'Pullman',
    'West Virginia': 'Morgantown',
    'Western Kentucky': 'Bowling Green',
    'Western Michigan': 'Kalamazoo',
    'Wisconsin': 'Madison',
    'Wyoming': 'Laramie',
}

state = {
    'Air Force': 'Colorado',
    'Akron': 'Ohio',
    'Alabama': 'Alabama',
    'Appalachian State': 'North Carolina',
    'Arizona': 'Arizona',
    'Arizona State': 'Arizona',
    'Arkansas': 'Arkansas',
    'Arkansas State': 'Arkansas',
    'Army': 'New York',
    'Auburn': 'Alabama',
    'Ball State': 'Indiana',
    'Baylor': 'Texas',
    'Boise State': 'Idaho',
    'Boston College': 'Massachusetts',
    'Bowling Green': 'Ohio',
    'Buffalo': 'New York',
    'BYU': 'Utah',
    'California': 'California',
    'Central Michigan': 'Michigan',
    'Charlotte': 'North Carolina',
    'Cincinnati': 'Ohio',
    'Clemson': 'South Carolina',
    'Coastal Carolina': 'South Carolina',
    'Colorado': 'Colorado',
    'Colorado State': 'Colorado',
    'Duke': 'North Carolina',
    'East Carolina': 'North Carolina',
    'Eastern Michigan': 'Michigan',
    'FIU': 'Florida',
    'Florida': 'Florida',
    'Florida Atlantic': 'Florida',
    'Florida State': 'Florida',
    'Fresno State': 'California',
    'Georgia': 'Georgia',
    'Georgia Southern': 'Georgia',
    'Georgia State': 'Georgia',
    'Georgia Tech': 'Georgia',
    'Hawaii': 'Hawaii',
    'Houston': 'Texas',
    'Illinois': 'Illinois',
    'Indiana': 'Indiana',
    'Iowa': 'Iowa',
    'Iowa State': 'Iowa',
    'James Madison': 'Virginia',
    'Kansas': 'Kansas',
    'Kansas State': 'Kansas',
    'Kent State': 'Ohio',
    'Kentucky': 'Kentucky',
    'Liberty': 'Virginia',
    'Louisiana': 'Louisiana',
    'Louisiana Tech': 'Louisiana',
    'Louisiana-Monroe': 'Louisiana',
    'Louisville': 'Kentucky',
    'LSU': 'Louisiana',
    'Marshall': 'West Virginia',
    'Maryland': 'Maryland',
    'Memphis': 'Tennessee',
    'Miami (FL)': 'Florida',
    'Miami (OH)': 'Ohio',
    'Michigan': 'Michigan',
    'Michigan State': 'Michigan',
    'Middle Tennessee': 'Tennessee',
    'Minnesota': 'Minnesota',
    'Mississippi State': 'Mississippi',
    'Missouri': 'Missouri',
    'Navy': 'Maryland',
    'NC State': 'North Carolina',
    'Nebraska': 'Nebraska',
    'Nevada': 'Nevada',
    'New Mexico': 'New Mexico',
    'New Mexico State': 'New Mexico',
    'North Carolina': 'North Carolina',
    'North Texas': 'Texas',
    'Northern Illinois': 'Illinois',
    'Northwestern': 'Illinois',
    'Notre Dame': 'Indiana',
    'Ohio': 'Ohio',
    'Ohio State': 'Ohio',
    'Oklahoma': 'Oklahoma',
    'Oklahoma State': 'Oklahoma',
    'Old Dominion': 'Virginia',
    'Ole Miss': 'Mississippi',
    'Oregon': 'Oregon',
    'Oregon State': 'Oregon',
    'Penn State': 'Pennsylvania',
    'Pittsburgh': 'Pennsylvania',
    'Purdue': 'Indiana',
    'Rice': 'Texas',
    'Rutgers': 'New Jersey',
    'San Diego State': 'California',
    'San Jose State': 'California',
    'SMU': 'Texas',
    'South Alabama': 'Alabama',
    'South Carolina': 'South Carolina',
    'South Florida': 'Florida',
    'Southern Miss': 'Mississippi',
    'Stanford': 'California',
    'Syracuse': 'New York',
    'TCU': 'Texas',
    'Temple': 'Pennsylvania',
    'Tennessee': 'Tennessee',
    'Texas': 'Texas',
    'Texas A&M': 'Texas',
    'Texas State': 'Texas',
    'Texas Tech': 'Texas',
    'Toledo': 'Ohio',
    'Troy': 'Alabama',
    'Tulane': 'Louisiana',
    'Tulsa': 'Oklahoma',
    'UAB': 'Alabama',
    'UCF': 'Florida',
    'UCLA': 'California',
    'UConn': 'Connecticut',
    'UMass': 'Massachusetts',
    'UNLV': 'Nevada',
    'USC': 'California',
    'Utah': 'Utah',
    'Utah State': 'Utah',
    'UTEP': 'Texas',
    'UTSA': 'Texas',
    'Vanderbilt': 'Tennessee',
    'Virginia': 'Virginia',
    'Virginia Tech': 'Virginia',
    'Wake Forest': 'North Carolina',
    'Washington': 'Washington',
    'Washington State': 'Washington',
    'West Virginia': 'West Virginia',
    'Western Kentucky': 'Kentucky',
    'Western Michigan': 'Michigan',
    'Wisconsin': 'Wisconsin',
    'Wyoming': 'Wyoming',
}

conference = {
    'Air Force': 'Mountain West',
    'Akron': 'MAC',
    'Alabama': 'SEC',
    'Appalachian State': 'Sun Belt',
    'Arizona': 'Pac-12',
    'Arizona State': 'Pac-12',
    'Arkansas': 'SEC',
    'Arkansas State': 'Sun Belt',
    'Army': 'Independent',
    'Auburn': 'SEC',
    'Ball State': 'MAC',
    'Baylor': 'Big 12',
    'Boise State': 'Mountain West',
    'Boston College': 'ACC',
    'Bowling Green': 'MAC',
    'Buffalo': 'MAC',
    'BYU': 'Independent',
    'California': 'Pac-12',
    'Central Michigan': 'MAC',
    'Charlotte': 'C-USA',
    'Cincinnati': 'American',
    'Clemson': 'ACC',
    'Coastal Carolina': 'Sun Belt',
    'Colorado': 'Pac-12',
    'Colorado State': 'Mountain West',
    'Duke': 'ACC',
    'East Carolina': 'American',
    'Eastern Michigan': 'MAC',
    'FIU': 'C-USA',
    'Florida': 'SEC',
    'Florida Atlantic': 'C-USA',
    'Florida State': 'ACC',
    'Fresno State': 'Mountain West',
    'Georgia': 'SEC',
    'Georgia Southern': 'Sun Belt',
    'Georgia State': 'Sun Belt',
    'Georgia Tech': 'ACC',
    'Hawaii': 'Mountain West',
    'Houston': 'American',
    'Illinois': 'Big Ten',
    'Indiana': 'Big Ten',
    'Iowa': 'Big Ten',
    'Iowa State': 'Big 12',
    'James Madison': 'Sun Belt',
    'Kansas': 'Big 12',
    'Kansas State': 'Big 12',
    'Kent State': 'MAC',
    'Kentucky': 'SEC',
    'Liberty': 'Independent',
    'Louisiana': 'Sun Belt',
    'Louisiana Tech': 'C-USA',
    'Louisiana-Monroe': 'Sun Belt',
    'Louisville': 'ACC',
    'LSU': 'SEC',
    'Marshall': 'Sun Belt',
    'Maryland': 'Big Ten',
    'Memphis': 'American',
    'Miami (FL)': 'ACC',
    'Miami (OH)': 'MAC',
    'Michigan': 'Big Ten',
    'Michigan State': 'Big Ten',
    'Middle Tennessee': 'C-USA',
    'Minnesota': 'Big Ten',
    'Mississippi State': 'SEC',
    'Missouri': 'SEC',
    'Navy': 'American',
    'NC State': 'ACC',
    'Nebraska': 'Big Ten',
    'Nevada': 'Mountain West',
    'New Mexico': 'Mountain West',
    'New Mexico State': 'Independent',
    'North Carolina': 'ACC',
    'North Texas': 'C-USA',
    'Northern Illinois': 'MAC',
    'Northwestern': 'Big Ten',
    'Notre Dame': 'Independent',
    'Ohio': 'MAC',
    'Ohio State': 'Big Ten',
    'Oklahoma': 'Big 12',
    'Oklahoma State': 'Big 12',
    'Old Dominion': 'Sun Belt',
    'Ole Miss': 'SEC',
    'Oregon': 'Pac-12',
    'Oregon State': 'Pac-12',
    'Penn State': 'Big Ten',
    'Pittsburgh': 'ACC',
    'Purdue': 'Big Ten',
    'Rice': 'C-USA',
    'Rutgers': 'Big Ten',
    'San Diego State': 'Mountain West',
    'San Jose State': 'Mountain West',
    'SMU': 'American',
    'South Alabama': 'Sun Belt',
    'South Carolina': 'SEC',
    'South Florida': 'American',
    'Southern Miss': 'Sun Belt',
    'Stanford': 'Pac-12',
    'Syracuse': 'ACC',
    'TCU': 'Big 12',
    'Temple': 'American',
    'Tennessee': 'SEC',
    'Texas': 'Big 12',
    'Texas A&M': 'SEC',
    'Texas State': 'Sun Belt',
    'Texas Tech': 'Big 12',
    'Toledo': 'MAC',
    'Troy': 'Sun Belt',
    'Tulane': 'American',
    'Tulsa': 'American',
    'UAB': 'C-USA',
    'UCF': 'American',
    'UCLA': 'Pac-12',
    'UConn': 'Independent',
    'UMass': 'Independent',
    'UNLV': 'Mountain West',
    'USC': 'Pac-12',
    'Utah': 'Pac-12',
    'Utah State': 'Mountain West',
    'UTEP': 'C-USA',
    'UTSA': 'C-USA',
    'Vanderbilt': 'SEC',
    'Virginia': 'ACC',
    'Virginia Tech': 'ACC',
    'Wake Forest': 'ACC',
    'Washington': 'Pac-12',
    'Washington State': 'Pac-12',
    'West Virginia': 'Big 12',
    'Western Kentucky': 'C-USA',
    'Western Michigan': 'MAC',
    'Wisconsin': 'Big Ten',
    'Wyoming': 'Mountain West',
}

enrollment = {
    'Air Force': 4181,
    'Akron': 14516,
    'Alabama': 38316,
    'Appalachian State': 20641,
    'Arizona': 49471,
    'Arizona State': 77881,
    'Arkansas': 29068,
    'Arkansas State': 12863,
    'Army': 4594,
    'Auburn': 31526,
    'Ball State': 19337,
    'Baylor': 20626,
    'Boise State': 25830,
    'Boston College': 15046,
    'Bowling Green': 17645,
    'Buffalo': 32332,
    'BYU': 34802,
    'California': 45435,
    'Central Michigan': 15465,
    'Charlotte': 30448,
    'Cincinnati': 40281,
    'Clemson': 27341,
    'Coastal Carolina': 10473,
    'Colorado': 37956,
    'Colorado State': 32777,
    'Duke': 17620,
    'East Carolina': 28021,
    'Eastern Michigan': 15370,
    'FIU': 56732,
    'Florida': 55781,
    'Florida Atlantic': 30155,
    'Florida State': 45130,
    'Fresno State': 24585,
    'Georgia': 40118,
    'Georgia Southern': 27091,
    'Georgia State': 55466,
    'Georgia Tech': 43844,
    'Hawaii': 19097,
    'Houston': 47031,
    'Illinois': 56607,
    'Indiana': 45328,
    'Iowa': 29909,
    'Iowa State': 30708,
    'James Madison': 22166,
    'Kansas': 26780,
    'Kansas State': 20229,
    'Kent State': 26597,
    'Kentucky': 30390,
    'Liberty': 95148,
    'Louisiana': 16225,
    'Louisiana Tech': 11037,
    'Louisiana-Monroe': 8565,
    'Louisville': 22140,
    'LSU': 35912,
    'Marshall': 11125,
    'Maryland': 41272,
    'Memphis': 21622,
    'Miami (FL)': 19096,
    'Miami (OH)': 19216,
    'Michigan': 50278,
    'Michigan State': 49659,
    'Middle Tennessee': 20857,
    'Minnesota': 52376,
    'Mississippi State': 23086,
    'Missouri': 31412,
    'Navy': 4528,
    'NC State': 36831,
    'Nebraska': 24431,
    'Nevada': 21034,
    'New Mexico': 21738,
    'New Mexico State': 13904,
    'North Carolina': 31733,
    'North Texas': 42454,
    'Northern Illinois': 16234,
    'Northwestern': 22933,
    'Notre Dame': 13139,
    'Ohio': 24429,
    'Ohio State': 61677,
    'Oklahoma': 28042,
    'Oklahoma State': 24660,
    'Old Dominion': 23494,
    'Ole Miss': 21203,
    'Oregon': 22257,
    'Oregon State': 33193,
    'Penn State': 47560,
    'Pittsburgh': 29238,
    'Purdue': 49639,
    'Rice': 8285,
    'Rutgers': 50804,
    'San Diego State': 35732,
    'San Jose State': 37133,
    'SMU': 12385,
    'South Alabama': 13992,
    'South Carolina': 35471,
    'South Florida': 44322,
    'Southern Miss': 14146,
    'Stanford': 17680,
    'Syracuse': 21772,
    'TCU': 11938,
    'Temple': 35626,
    'Tennessee': 31701,
    'Texas': 51991,
    'Texas A&M': 72530,
    'Texas State': 37864,
    'Texas Tech': 40542,
    'Toledo': 17045,
    'Troy': 14901,
    'Tulane': 13127,
    'Tulsa': 3832,
    'UAB': 22289,
    'UCF': 70406,
    'UCLA': 47516,
    'UConn': 32146,
    'UMass': 32045,
    'UNLV': 30679,
    'USC': 49318,
    'Utah': 34464,
    'Utah State': 27426,
    'UTEP': 24003,
    'UTSA': 34734,
    'Vanderbilt': 13796,
    'Virginia': 26026,
    'Virginia Tech': 37279,
    'Wake Forest': 8947,
    'Washington': 52439,
    'Washington State': 29843,
    'West Virginia': 25474,
    'Western Kentucky': 16750,
    'Western Michigan': 19038,
    'Wisconsin': 47932,
    'Wyoming': 11479,
}

fbs_teams = {
    'Air Force': ['Falcons', 'Colorado Springs', 'Colorado', 4181, 'Mountain West'],
    'Akron': ['Zips', 'Akron', 'Ohio', 14516, 'MAC'],
    'Alabama': ['Crimson Tide', 'Tuscaloosa', 'Alabama', 38316, 'SEC'],
    'Appalachian State': ['Mountaineers', 'Boone', 'North Carolina', 20641, 'Sun Belt'],
    'Arizona': ['Wildcats', 'Tucson', 'Arizona', 49471, 'Pac-12'],
    'Arizona State': ['Sun Devils', 'Tempe', 'Arizona', 77881, 'Pac-12'],
    'Arkansas': ['Razorbacks', 'Fayetteville', 'Arkansas', 29068, 'SEC'],
    'Arkansas State': ['Red Wolves', 'Jonesboro', 'Arkansas', 12863, 'Sun Belt'],
    'Army': ['Black Knights', 'West Point', 'New York', 4594, 'Independent'],
    'Auburn': ['Tigers', 'Auburn', 'Alabama', 31526, 'SEC'],
    'Ball State': ['Cardinals', 'Muncie', 'Indiana', 19337, 'MAC'],
    'Baylor': ['Bears', 'Waco', 'Texas', 20626, 'Big 12'],
    'Boise State': ['Broncos', 'Boise', 'Idaho', 25830, 'Mountain West'],
    'Boston College': ['Eagles', 'Chestnut Hill', 'Massachusetts', 15046, 'ACC'],
    'Bowling Green': ['Falcons', 'Bowling Green', 'Ohio', 17645, 'MAC'],
    'Buffalo': ['Bulls', 'Buffalo', 'New York', 32332, 'MAC'],
    'BYU': ['Cougars', 'Provo', 'Utah', 34802, 'Independent'],
    'California': ['Golden Bears', 'Berkeley', 'California', 45435, 'Pac-12'],
    'Central Michigan': ['Chippewas', 'Mount Pleasant', 'Michigan', 15465, 'MAC'],
    'Charlotte': ['49ers', 'Charlotte', 'North Carolina', 30448, 'C-USA'],
    'Cincinnati': ['Bearcats', 'Cincinnati', 'Ohio', 40281, 'American'],
    'Clemson': ['Tigers', 'Clemson', 'South Carolina', 27341, 'ACC'],
    'Coastal Carolina': ['Chanticleers', 'Conway', 'South Carolina', 10473, 'Sun Belt'],
    'Colorado': ['Buffaloes', 'Boulder', 'Colorado', 37956, 'Pac-12'],
    'Colorado State': ['Rams', 'Fort Collins', 'Colorado', 32777, 'Mountain West'],
    'Duke': ['Blue Devils', 'Durham', 'North Carolina', 17620, 'ACC'],
    'East Carolina': ['Pirates', 'Greenville', 'North Carolina', 28021, 'American'],
    'Eastern Michigan': ['Eagles', 'Ypsilanti', 'Michigan', 15370, 'MAC'],
    'FIU': ['Panthers', 'Miami', 'Florida', 56732, 'C-USA'],
    'Florida': ['Gators', 'Gainesville', 'Florida', 55781, 'SEC'],
    'Florida Atlantic': ['Owls', 'Boca Raton', 'Florida', 30155, 'C-USA'],
    'Florida State': ['Seminoles', 'Tallahassee', 'Florida', 45130, 'ACC'],
    'Fresno State': ['Bulldogs', 'Fresno', 'California', 24585, 'Mountain West'],
    'Georgia': ['Bulldogs', 'Athens', 'Georgia', 40118, 'SEC'],
    'Georgia Southern': ['Eagles', 'Statesboro', 'Georgia', 27091, 'Sun Belt'],
    'Georgia State': ['Panthers', 'Atlanta', 'Georgia', 55466, 'Sun Belt'],
    'Georgia Tech': ['Yellow Jackets', 'Atlanta', 'Georgia', 43844, 'ACC'],
    'Hawaii': ['Rainbow Warriors', 'Honolulu', 'Hawaii', 19097, 'Mountain West'],
    'Houston': ['Cougars', 'Houston', 'Texas', 47031, 'American'],
    'Illinois': ['Fighting Illini', 'Urbana?Champaign', 'Illinois', 56607, 'Big Ten'],
    'Indiana': ['Hoosiers', 'Bloomington', 'Indiana', 45328, 'Big Ten'],
    'Iowa': ['Hawkeyes', 'Iowa City', 'Iowa', 29909, 'Big Ten'],
    'Iowa State': ['Cyclones', 'Ames', 'Iowa', 30708, 'Big 12'],
    'James Madison': ['Dukes', 'Harrisonburg', 'Virginia', 22166, 'Sun Belt'],
    'Kansas': ['Jayhawks', 'Lawrence', 'Kansas', 26780, 'Big 12'],
    'Kansas State': ['Wildcats', 'Manhattan', 'Kansas', 20229, 'Big 12'],
    'Kent State': ['Golden Flashes', 'Kent', 'Ohio', 26597, 'MAC'],
    'Kentucky': ['Wildcats', 'Lexington', 'Kentucky', 30390, 'SEC'],
    'Liberty': ['Flames', 'Lynchburg', 'Virginia', 95148, 'Independent'],
    'Louisiana': ["Ragin' Cajuns", 'Lafayette', 'Louisiana', 16225, 'Sun Belt'],
    'Louisiana Tech': ['Bulldogs', 'Ruston', 'Louisiana', 11037, 'C-USA'],
    'Louisiana-Monroe': ['Warhawks', 'Monroe', 'Louisiana', 8565, 'Sun Belt'],
    'Louisville': ['Cardinals', 'Louisville', 'Kentucky', 22140, 'ACC'],
    'LSU': ['Tigers', 'Baton Rouge', 'Louisiana', 35912, 'SEC'],
    'Marshall': ['Thundering Herd', 'Huntington', 'West Virginia', 11125, 'Sun Belt'],
    'Maryland': ['Terrapins', 'College Park', 'Maryland', 41272, 'Big Ten'],
    'Memphis': ['Tigers', 'Memphis', 'Tennessee', 21622, 'American'],
    'Miami (FL)': ['Hurricanes', 'Coral Gables', 'Florida', 19096, 'ACC'],
    'Miami (OH)': ['RedHawks', 'Oxford', 'Ohio', 19216, 'MAC'],
    'Michigan': ['Wolverines', 'Ann Arbor', 'Michigan', 50278, 'Big Ten'],
    'Michigan State': ['Spartans', 'East Lansing', 'Michigan', 49659, 'Big Ten'],
    'Middle Tennessee': ['Blue Raiders', 'Murfreesboro', 'Tennessee', 20857, 'C-USA'],
    'Minnesota': ['Golden Gophers', 'Minneapolis', 'Minnesota', 52376, 'Big Ten'],
    'Mississippi State': ['Bulldogs', 'Starkville', 'Mississippi', 23086, 'SEC'],
    'Missouri': ['Tigers', 'Columbia', 'Missouri', 31412, 'SEC'],
    'Navy': ['Midshipmen', 'Annapolis', 'Maryland', 4528, 'American'],
    'NC State': ['Wolfpack', 'Raleigh', 'North Carolina', 36831, 'ACC'],
    'Nebraska': ['Cornhuskers', 'Lincoln', 'Nebraska', 24431, 'Big Ten'],
    'Nevada': ['Wolf Pack', 'Reno', 'Nevada', 21034, 'Mountain West'],
    'New Mexico': ['Lobos', 'Albuquerque', 'New Mexico', 21738, 'Mountain West'],
    'New Mexico State': ['Aggies', 'Las Cruces', 'New Mexico', 13904, 'Independent'],
    'North Carolina': ['Tar Heels', 'Chapel Hill', 'North Carolina', 31733, 'ACC'],
    'North Texas': ['Mean Green', 'Denton', 'Texas', 42454, 'C-USA'],
    'Northern Illinois': ['Huskies', 'DeKalb', 'Illinois', 16234, 'MAC'],
    'Northwestern': ['Wildcats', 'Evanston', 'Illinois', 22933, 'Big Ten'],
    'Notre Dame': ['Fighting Irish', 'South Bend', 'Indiana', 13139, 'Independent'],
    'Ohio': ['Bobcats', 'Athens', 'Ohio', 24429, 'MAC'],
    'Ohio State': ['Buckeyes', 'Columbus', 'Ohio', 61677, 'Big Ten'],
    'Oklahoma': ['Sooners', 'Norman', 'Oklahoma', 28042, 'Big 12'],
    'Oklahoma State': ['Cowboys', 'Stillwater', 'Oklahoma', 24660, 'Big 12'],
    'Old Dominion': ['Monarchs', 'Norfolk', 'Virginia', 23494, 'Sun Belt'],
    'Ole Miss': ['Rebels', 'Oxford', 'Mississippi', 21203, 'SEC'],
    'Oregon': ['Ducks', 'Eugene', 'Oregon', 22257, 'Pac-12'],
    'Oregon State': ['Beavers', 'Corvallis', 'Oregon', 33193, 'Pac-12'],
    'Penn State': ['Nittany Lions', 'University Park', 'Pennsylvania', 47560, 'Big Ten'],
    'Pittsburgh': ['Panthers', 'Pittsburgh', 'Pennsylvania', 29238, 'ACC'],
    'Purdue': ['Boilermakers', 'West Lafayette', 'Indiana', 49639, 'Big Ten'],
    'Rice': ['Owls', 'Houston', 'Texas', 8285, 'C-USA'],
    'Rutgers': ['Scarlet Knights', 'Piscataway', 'New Jersey', 50804, 'Big Ten'],
    'San Diego State': ['Aztecs', 'San Diego', 'California', 35732, 'Mountain West'],
    'San Jose State': ['Spartans', 'San Jose', 'California', 37133, 'Mountain West'],
    'SMU': ['Mustangs', 'University Park', 'Texas', 12385, 'American'],
    'South Alabama': ['Jaguars', 'Mobile', 'Alabama', 13992, 'Sun Belt'],
    'South Carolina': ['Gamecocks', 'Columbia', 'South Carolina', 35471, 'SEC'],
    'South Florida': ['Bulls', 'Tampa', 'Florida', 44322, 'American'],
    'Southern Miss': ['Golden Eagles', 'Hattiesburg', 'Mississippi', 14146, 'Sun Belt'],
    'Stanford': ['Cardinal', 'Stanford', 'California', 17680, 'Pac-12'],
    'Syracuse': ['Orange', 'Syracuse', 'New York', 21772, 'ACC'],
    'TCU': ['Horned Frogs', 'Fort Worth', 'Texas', 11938, 'Big 12'],
    'Temple': ['Owls', 'Philadelphia', 'Pennsylvania', 35626, 'American'],
    'Tennessee': ['Volunteers', 'Knoxville', 'Tennessee', 31701, 'SEC'],
    'Texas': ['Longhorns', 'Austin', 'Texas', 51991, 'Big 12'],
    'Texas A&M': ['Aggies', 'College Station', 'Texas', 72530, 'SEC'],
    'Texas State': ['Bobcats', 'San Marcos', 'Texas', 37864, 'Sun Belt'],
    'Texas Tech': ['Red Raiders', 'Lubbock', 'Texas', 40542, 'Big 12'],
    'Toledo': ['Rockets', 'Toledo', 'Ohio', 17045, 'MAC'],
    'Troy': ['Trojans', 'Troy', 'Alabama', 14901, 'Sun Belt'],
    'Tulane': ['Green Wave', 'New Orleans', 'Louisiana', 13127, 'American'],
    'Tulsa': ['Golden Hurricane', 'Tulsa', 'Oklahoma', 3832, 'American'],
    'UAB': ['Blazers', 'Birmingham', 'Alabama', 22289, 'C-USA'],
    'UCF': ['Knights', 'Orlando', 'Florida', 70406, 'American'],
    'UCLA': ['Bruins', 'Los Angeles', 'California', 47516, 'Pac-12'],
    'UConn': ['Huskies', 'Storrs', 'Connecticut', 32146, 'Independent'],
    'UMass': ['Minutemen', 'Amherst', 'Massachusetts', 32045, 'Independent'],
    'UNLV': ['Rebels', 'Las Vegas', 'Nevada', 30679, 'Mountain West'],
    'USC': ['Trojans', 'Los Angeles', 'California', 49318, 'Pac-12'],
    'Utah': ['Utes', 'Salt Lake City', 'Utah', 34464, 'Pac-12'],
    'Utah State': ['Aggies', 'Logan', 'Utah', 27426, 'Mountain West'],
    'UTEP': ['Miners', 'El Paso', 'Texas', 24003, 'C-USA'],
    'UTSA': ['Roadrunners', 'San Antonio', 'Texas', 34734, 'C-USA'],
    'Vanderbilt': ['Commodores', 'Nashville', 'Tennessee', 13796, 'SEC'],
    'Virginia': ['Cavaliers', 'Charlottesville', 'Virginia', 26026, 'ACC'],
    'Virginia Tech': ['Hokies', 'Blacksburg', 'Virginia', 37279, 'ACC'],
    'Wake Forest': ['Demon Deacons', 'Winston-Salem', 'North Carolina', 8947, 'ACC'],
    'Washington': ['Huskies', 'Seattle', 'Washington', 52439, 'Pac-12'],
    'Washington State': ['Cougars', 'Pullman', 'Washington', 29843, 'Pac-12'],
    'West Virginia': ['Mountaineers', 'Morgantown', 'West Virginia', 25474, 'Big 12'],
    'Western Kentucky': ['Hilltoppers', 'Bowling Green', 'Kentucky', 16750, 'C-USA'],
    'Western Michigan': ['Broncos', 'Kalamazoo', 'Michigan', 19038, 'MAC'],
    'Wisconsin': ['Badgers', 'Madison', 'Wisconsin', 47932, 'Big Ten'],
    'Wyoming': ['Cowboys', 'Laramie', 'Wyoming', 11479, 'Mountain West'],
}

fbs_teams_dict = {
    'Air Force': {'nickname': 'Falcons', 'city': 'Colorado Springs', 'state': 'Colorado', 'enrollment': 4181, 'conference': 'Mountain West'},
    'Akron': {'nickname': 'Zips', 'city': 'Akron', 'state': 'Ohio', 'enrollment': 14516, 'conference': 'MAC'},
    'Alabama': {'nickname': 'Crimson Tide', 'city': 'Tuscaloosa', 'state': 'Alabama', 'enrollment': 38316, 'conference': 'SEC'},
    'Appalachian State': {'nickname': 'Mountaineers', 'city': 'Boone', 'state': 'North Carolina', 'enrollment': 20641, 'conference': 'Sun Belt'},
    'Arizona': {'nickname': 'Wildcats', 'city': 'Tucson', 'state': 'Arizona', 'enrollment': 49471, 'conference': 'Pac-12'},
    'Arizona State': {'nickname': 'Sun Devils', 'city': 'Tempe', 'state': 'Arizona', 'enrollment': 77881, 'conference': 'Pac-12'},
    'Arkansas': {'nickname': 'Razorbacks', 'city': 'Fayetteville', 'state': 'Arkansas', 'enrollment': 29068, 'conference': 'SEC'},
    'Arkansas State': {'nickname': 'Red Wolves', 'city': 'Jonesboro', 'state': 'Arkansas', 'enrollment': 12863, 'conference': 'Sun Belt'},
    'Army': {'nickname': 'Black Knights', 'city': 'West Point', 'state': 'New York', 'enrollment': 4594, 'conference': 'Independent'},
    'Auburn': {'nickname': 'Tigers', 'city': 'Auburn', 'state': 'Alabama', 'enrollment': 31526, 'conference': 'SEC'},
    'Ball State': {'nickname': 'Cardinals', 'city': 'Muncie', 'state': 'Indiana', 'enrollment': 19337, 'conference': 'MAC'},
    'Baylor': {'nickname': 'Bears', 'city': 'Waco', 'state': 'Texas', 'enrollment': 20626, 'conference': 'Big 12'},
    'Boise State': {'nickname': 'Broncos', 'city': 'Boise', 'state': 'Idaho', 'enrollment': 25830, 'conference': 'Mountain West'},
    'Boston College': {'nickname': 'Eagles', 'city': 'Chestnut Hill', 'state': 'Massachusetts', 'enrollment': 15046, 'conference': 'ACC'},
    'Bowling Green': {'nickname': 'Falcons', 'city': 'Bowling Green', 'state': 'Ohio', 'enrollment': 17645, 'conference': 'MAC'},
    'Buffalo': {'nickname': 'Bulls', 'city': 'Buffalo', 'state': 'New York', 'enrollment': 32332, 'conference': 'MAC'},
    'BYU': {'nickname': 'Cougars', 'city': 'Provo', 'state': 'Utah', 'enrollment': 34802, 'conference': 'Independent'},
    'California': {'nickname': 'Golden Bears', 'city': 'Berkeley', 'state': 'California', 'enrollment': 45435, 'conference': 'Pac-12'},
    'Central Michigan': {'nickname': 'Chippewas', 'city': 'Mount Pleasant', 'state': 'Michigan', 'enrollment': 15465, 'conference': 'MAC'},
    'Charlotte': {'nickname': '49ers', 'city': 'Charlotte', 'state': 'North Carolina', 'enrollment': 30448, 'conference': 'C-USA'},
    'Cincinnati': {'nickname': 'Bearcats', 'city': 'Cincinnati', 'state': 'Ohio', 'enrollment': 40281, 'conference': 'American'},
    'Clemson': {'nickname': 'Tigers', 'city': 'Clemson', 'state': 'South Carolina', 'enrollment': 27341, 'conference': 'ACC'},
    'Coastal Carolina': {'nickname': 'Chanticleers', 'city': 'Conway', 'state': 'South Carolina', 'enrollment': 10473, 'conference': 'Sun Belt'},
    'Colorado': {'nickname': 'Buffaloes', 'city': 'Boulder', 'state': 'Colorado', 'enrollment': 37956, 'conference': 'Pac-12'},
    'Colorado State': {'nickname': 'Rams', 'city': 'Fort Collins', 'state': 'Colorado', 'enrollment': 32777, 'conference': 'Mountain West'},
    'Duke': {'nickname': 'Blue Devils', 'city': 'Durham', 'state': 'North Carolina', 'enrollment': 17620, 'conference': 'ACC'},
    'East Carolina': {'nickname': 'Pirates', 'city': 'Greenville', 'state': 'North Carolina', 'enrollment': 28021, 'conference': 'American'},
    'Eastern Michigan': {'nickname': 'Eagles', 'city': 'Ypsilanti', 'state': 'Michigan', 'enrollment': 15370, 'conference': 'MAC'},
    'FIU': {'nickname': 'Panthers', 'city': 'Miami', 'state': 'Florida', 'enrollment': 56732, 'conference': 'C-USA'},
    'Florida': {'nickname': 'Gators', 'city': 'Gainesville', 'state': 'Florida', 'enrollment': 55781, 'conference': 'SEC'},
    'Florida Atlantic': {'nickname': 'Owls', 'city': 'Boca Raton', 'state': 'Florida', 'enrollment': 30155, 'conference': 'C-USA'},
    'Florida State': {'nickname': 'Seminoles', 'city': 'Tallahassee', 'state': 'Florida', 'enrollment': 45130, 'conference': 'ACC'},
    'Fresno State': {'nickname': 'Bulldogs', 'city': 'Fresno', 'state': 'California', 'enrollment': 24585, 'conference': 'Mountain West'},
    'Georgia': {'nickname': 'Bulldogs', 'city': 'Athens', 'state': 'Georgia', 'enrollment': 40118, 'conference': 'SEC'},
    'Georgia Southern': {'nickname': 'Eagles', 'city': 'Statesboro', 'state': 'Georgia', 'enrollment': 27091, 'conference': 'Sun Belt'},
    'Georgia State': {'nickname': 'Panthers', 'city': 'Atlanta', 'state': 'Georgia', 'enrollment': 55466, 'conference': 'Sun Belt'},
    'Georgia Tech': {'nickname': 'Yellow Jackets', 'city': 'Atlanta', 'state': 'Georgia', 'enrollment': 43844, 'conference': 'ACC'},
    'Hawaii': {'nickname': 'Rainbow Warriors', 'city': 'Honolulu', 'state': 'Hawaii', 'enrollment': 19097, 'conference': 'Mountain West'},
    'Houston': {'nickname': 'Cougars', 'city': 'Houston', 'state': 'Texas', 'enrollment': 47031, 'conference': 'American'},
    'Illinois': {'nickname': 'Fighting Illini', 'city': 'Urbana?Champaign', 'state': 'Illinois', 'enrollment': 56607, 'conference': 'Big Ten'},
    'Indiana': {'nickname': 'Hoosiers', 'city': 'Bloomington', 'state': 'Indiana', 'enrollment': 45328, 'conference': 'Big Ten'},
    'Iowa': {'nickname': 'Hawkeyes', 'city': 'Iowa City', 'state': 'Iowa', 'enrollment': 29909, 'conference': 'Big Ten'},
    'Iowa State': {'nickname': 'Cyclones', 'city': 'Ames', 'state': 'Iowa', 'enrollment': 30708, 'conference': 'Big 12'},
    'James Madison': {'nickname': 'Dukes', 'city': 'Harrisonburg', 'state': 'Virginia', 'enrollment': 22166, 'conference': 'Sun Belt'},
    'Kansas': {'nickname': 'Jayhawks', 'city': 'Lawrence', 'state': 'Kansas', 'enrollment': 26780, 'conference': 'Big 12'},
    'Kansas State': {'nickname': 'Wildcats', 'city': 'Manhattan', 'state': 'Kansas', 'enrollment': 20229, 'conference': 'Big 12'},
    'Kent State': {'nickname': 'Golden Flashes', 'city': 'Kent', 'state': 'Ohio', 'enrollment': 26597, 'conference': 'MAC'},
    'Kentucky': {'nickname': 'Wildcats', 'city': 'Lexington', 'state': 'Kentucky', 'enrollment': 30390, 'conference': 'SEC'},
    'Liberty': {'nickname': 'Flames', 'city': 'Lynchburg', 'state': 'Virginia', 'enrollment': 95148, 'conference': 'Independent'},
    'Louisiana': {'nickname': "Ragin' Cajuns", 'city': 'Lafayette', 'state': 'Louisiana', 'enrollment': 16225, 'conference': 'Sun Belt'},
    'Louisiana Tech': {'nickname': 'Bulldogs', 'city': 'Ruston', 'state': 'Louisiana', 'enrollment': 11037, 'conference': 'C-USA'},
    'Louisiana-Monroe': {'nickname': 'Warhawks', 'city': 'Monroe', 'state': 'Louisiana', 'enrollment': 8565, 'conference': 'Sun Belt'},
    'Louisville': {'nickname': 'Cardinals', 'city': 'Louisville', 'state': 'Kentucky', 'enrollment': 22140, 'conference': 'ACC'},
    'LSU': {'nickname': 'Tigers', 'city': 'Baton Rouge', 'state': 'Louisiana', 'enrollment': 35912, 'conference': 'SEC'},
    'Marshall': {'nickname': 'Thundering Herd', 'city': 'Huntington', 'state': 'West Virginia', 'enrollment': 11125, 'conference': 'Sun Belt'},
    'Maryland': {'nickname': 'Terrapins', 'city': 'College Park', 'state': 'Maryland', 'enrollment': 41272, 'conference': 'Big Ten'},
    'Memphis': {'nickname': 'Tigers', 'city': 'Memphis', 'state': 'Tennessee', 'enrollment': 21622, 'conference': 'American'},
    'Miami (FL)': {'nickname': 'Hurricanes', 'city': 'Coral Gables', 'state': 'Florida', 'enrollment': 19096, 'conference': 'ACC'},
    'Miami (OH)': {'nickname': 'RedHawks', 'city': 'Oxford', 'state': 'Ohio', 'enrollment': 19216, 'conference': 'MAC'},
    'Michigan': {'nickname': 'Wolverines', 'city': 'Ann Arbor', 'state': 'Michigan', 'enrollment': 50278, 'conference': 'Big Ten'},
    'Michigan State': {'nickname': 'Spartans', 'city': 'East Lansing', 'state': 'Michigan', 'enrollment': 49659, 'conference': 'Big Ten'},
    'Middle Tennessee': {'nickname': 'Blue Raiders', 'city': 'Murfreesboro', 'state': 'Tennessee', 'enrollment': 20857, 'conference': 'C-USA'},
    'Minnesota': {'nickname': 'Golden Gophers', 'city': 'Minneapolis', 'state': 'Minnesota', 'enrollment': 52376, 'conference': 'Big Ten'},
    'Mississippi State': {'nickname': 'Bulldogs', 'city': 'Starkville', 'state': 'Mississippi', 'enrollment': 23086, 'conference': 'SEC'},
    'Missouri': {'nickname': 'Tigers', 'city': 'Columbia', 'state': 'Missouri', 'enrollment': 31412, 'conference': 'SEC'},
    'Navy': {'nickname': 'Midshipmen', 'city': 'Annapolis', 'state': 'Maryland', 'enrollment': 4528, 'conference': 'American'},
    'NC State': {'nickname': 'Wolfpack', 'city': 'Raleigh', 'state': 'North Carolina', 'enrollment': 36831, 'conference': 'ACC'},
    'Nebraska': {'nickname': 'Cornhuskers', 'city': 'Lincoln', 'state': 'Nebraska', 'enrollment': 24431, 'conference': 'Big Ten'},
    'Nevada': {'nickname': 'Wolf Pack', 'city': 'Reno', 'state': 'Nevada', 'enrollment': 21034, 'conference': 'Mountain West'},
    'New Mexico': {'nickname': 'Lobos', 'city': 'Albuquerque', 'state': 'New Mexico', 'enrollment': 21738, 'conference': 'Mountain West'},
    'New Mexico State': {'nickname': 'Aggies', 'city': 'Las Cruces', 'state': 'New Mexico', 'enrollment': 13904, 'conference': 'Independent'},
    'North Carolina': {'nickname': 'Tar Heels', 'city': 'Chapel Hill', 'state': 'North Carolina', 'enrollment': 31733, 'conference': 'ACC'},
    'North Texas': {'nickname': 'Mean Green', 'city': 'Denton', 'state': 'Texas', 'enrollment': 42454, 'conference': 'C-USA'},
    'Northern Illinois': {'nickname': 'Huskies', 'city': 'DeKalb', 'state': 'Illinois', 'enrollment': 16234, 'conference': 'MAC'},
    'Northwestern': {'nickname': 'Wildcats', 'city': 'Evanston', 'state': 'Illinois', 'enrollment': 22933, 'conference': 'Big Ten'},
    'Notre Dame': {'nickname': 'Fighting Irish', 'city': 'South Bend', 'state': 'Indiana', 'enrollment': 13139, 'conference': 'Independent'},
    'Ohio': {'nickname': 'Bobcats', 'city': 'Athens', 'state': 'Ohio', 'enrollment': 24429, 'conference': 'MAC'},
    'Ohio State': {'nickname': 'Buckeyes', 'city': 'Columbus', 'state': 'Ohio', 'enrollment': 61677, 'conference': 'Big Ten'},
    'Oklahoma': {'nickname': 'Sooners', 'city': 'Norman', 'state': 'Oklahoma', 'enrollment': 28042, 'conference': 'Big 12'},
    'Oklahoma State': {'nickname': 'Cowboys', 'city': 'Stillwater', 'state': 'Oklahoma', 'enrollment': 24660, 'conference': 'Big 12'},
    'Old Dominion': {'nickname': 'Monarchs', 'city': 'Norfolk', 'state': 'Virginia', 'enrollment': 23494, 'conference': 'Sun Belt'},
    'Ole Miss': {'nickname': 'Rebels', 'city': 'Oxford', 'state': 'Mississippi', 'enrollment': 21203, 'conference': 'SEC'},
    'Oregon': {'nickname': 'Ducks', 'city': 'Eugene', 'state': 'Oregon', 'enrollment': 22257, 'conference': 'Pac-12'},
    'Oregon State': {'nickname': 'Beavers', 'city': 'Corvallis', 'state': 'Oregon', 'enrollment': 33193, 'conference': 'Pac-12'},
    'Penn State': {'nickname': 'Nittany Lions', 'city': 'University Park', 'state': 'Pennsylvania', 'enrollment': 47560, 'conference': 'Big Ten'},
    'Pittsburgh': {'nickname': 'Panthers', 'city': 'Pittsburgh', 'state': 'Pennsylvania', 'enrollment': 29238, 'conference': 'ACC'},
    'Purdue': {'nickname': 'Boilermakers', 'city': 'West Lafayette', 'state': 'Indiana', 'enrollment': 49639, 'conference': 'Big Ten'},
    'Rice': {'nickname': 'Owls', 'city': 'Houston', 'state': 'Texas', 'enrollment': 8285, 'conference': 'C-USA'},
    'Rutgers': {'nickname': 'Scarlet Knights', 'city': 'Piscataway', 'state': 'New Jersey', 'enrollment': 50804, 'conference': 'Big Ten'},
    'San Diego State': {'nickname': 'Aztecs', 'city': 'San Diego', 'state': 'California', 'enrollment': 35732, 'conference': 'Mountain West'},
    'San Jose State': {'nickname': 'Spartans', 'city': 'San Jose', 'state': 'California', 'enrollment': 37133, 'conference': 'Mountain West'},
    'SMU': {'nickname': 'Mustangs', 'city': 'University Park', 'state': 'Texas', 'enrollment': 12385, 'conference': 'American'},
    'South Alabama': {'nickname': 'Jaguars', 'city': 'Mobile', 'state': 'Alabama', 'enrollment': 13992, 'conference': 'Sun Belt'},
    'South Carolina': {'nickname': 'Gamecocks', 'city': 'Columbia', 'state': 'South Carolina', 'enrollment': 35471, 'conference': 'SEC'},
    'South Florida': {'nickname': 'Bulls', 'city': 'Tampa', 'state': 'Florida', 'enrollment': 44322, 'conference': 'American'},
    'Southern Miss': {'nickname': 'Golden Eagles', 'city': 'Hattiesburg', 'state': 'Mississippi', 'enrollment': 14146, 'conference': 'Sun Belt'},
    'Stanford': {'nickname': 'Cardinal', 'city': 'Stanford', 'state': 'California', 'enrollment': 17680, 'conference': 'Pac-12'},
    'Syracuse': {'nickname': 'Orange', 'city': 'Syracuse', 'state': 'New York', 'enrollment': 21772, 'conference': 'ACC'},
    'TCU': {'nickname': 'Horned Frogs', 'city': 'Fort Worth', 'state': 'Texas', 'enrollment': 11938, 'conference': 'Big 12'},
    'Temple': {'nickname': 'Owls', 'city': 'Philadelphia', 'state': 'Pennsylvania', 'enrollment': 35626, 'conference': 'American'},
    'Tennessee': {'nickname': 'Volunteers', 'city': 'Knoxville', 'state': 'Tennessee', 'enrollment': 31701, 'conference': 'SEC'},
    'Texas': {'nickname': 'Longhorns', 'city': 'Austin', 'state': 'Texas', 'enrollment': 51991, 'conference': 'Big 12'},
    'Texas A&M': {'nickname': 'Aggies', 'city': 'College Station', 'state': 'Texas', 'enrollment': 72530, 'conference': 'SEC'},
    'Texas State': {'nickname': 'Bobcats', 'city': 'San Marcos', 'state': 'Texas', 'enrollment': 37864, 'conference': 'Sun Belt'},
    'Texas Tech': {'nickname': 'Red Raiders', 'city': 'Lubbock', 'state': 'Texas', 'enrollment': 40542, 'conference': 'Big 12'},
    'Toledo': {'nickname': 'Rockets', 'city': 'Toledo', 'state': 'Ohio', 'enrollment': 17045, 'conference': 'MAC'},
    'Troy': {'nickname': 'Trojans', 'city': 'Troy', 'state': 'Alabama', 'enrollment': 14901, 'conference': 'Sun Belt'},
    'Tulane': {'nickname': 'Green Wave', 'city': 'New Orleans', 'state': 'Louisiana', 'enrollment': 13127, 'conference': 'American'},
    'Tulsa': {'nickname': 'Golden Hurricane', 'city': 'Tulsa', 'state': 'Oklahoma', 'enrollment': 3832, 'conference': 'American'},
    'UAB': {'nickname': 'Blazers', 'city': 'Birmingham', 'state': 'Alabama', 'enrollment': 22289, 'conference': 'C-USA'},
    'UCF': {'nickname': 'Knights', 'city': 'Orlando', 'state': 'Florida', 'enrollment': 70406, 'conference': 'American'},
    'UCLA': {'nickname': 'Bruins', 'city': 'Los Angeles', 'state': 'California', 'enrollment': 47516, 'conference': 'Pac-12'},
    'UConn': {'nickname': 'Huskies', 'city': 'Storrs', 'state': 'Connecticut', 'enrollment': 32146, 'conference': 'Independent'},
    'UMass': {'nickname': 'Minutemen', 'city': 'Amherst', 'state': 'Massachusetts', 'enrollment': 32045, 'conference': 'Independent'},
    'UNLV': {'nickname': 'Rebels', 'city': 'Las Vegas', 'state': 'Nevada', 'enrollment': 30679, 'conference': 'Mountain West'},
    'USC': {'nickname': 'Trojans', 'city': 'Los Angeles', 'state': 'California', 'enrollment': 49318, 'conference': 'Pac-12'},
    'Utah': {'nickname': 'Utes', 'city': 'Salt Lake City', 'state': 'Utah', 'enrollment': 34464, 'conference': 'Pac-12'},
    'Utah State': {'nickname': 'Aggies', 'city': 'Logan', 'state': 'Utah', 'enrollment': 27426, 'conference': 'Mountain West'},
    'UTEP': {'nickname': 'Miners', 'city': 'El Paso', 'state': 'Texas', 'enrollment': 24003, 'conference': 'C-USA'},
    'UTSA': {'nickname': 'Roadrunners', 'city': 'San Antonio', 'state': 'Texas', 'enrollment': 34734, 'conference': 'C-USA'},
    'Vanderbilt': {'nickname': 'Commodores', 'city': 'Nashville', 'state': 'Tennessee', 'enrollment': 13796, 'conference': 'SEC'},
    'Virginia': {'nickname': 'Cavaliers', 'city': 'Charlottesville', 'state': 'Virginia', 'enrollment': 26026, 'conference': 'ACC'},
    'Virginia Tech': {'nickname': 'Hokies', 'city': 'Blacksburg', 'state': 'Virginia', 'enrollment': 37279, 'conference': 'ACC'},
    'Wake Forest': {'nickname': 'Demon Deacons', 'city': 'Winston-Salem', 'state': 'North Carolina', 'enrollment': 8947, 'conference': 'ACC'},
    'Washington': {'nickname': 'Huskies', 'city': 'Seattle', 'state': 'Washington', 'enrollment': 52439, 'conference': 'Pac-12'},
    'Washington State': {'nickname': 'Cougars', 'city': 'Pullman', 'state': 'Washington', 'enrollment': 29843, 'conference': 'Pac-12'},
    'West Virginia': {'nickname': 'Mountaineers', 'city': 'Morgantown', 'state': 'West Virginia', 'enrollment': 25474, 'conference': 'Big 12'},
    'Western Kentucky': {'nickname': 'Hilltoppers', 'city': 'Bowling Green', 'state': 'Kentucky', 'enrollment': 16750, 'conference': 'C-USA'},
    'Western Michigan': {'nickname': 'Broncos', 'city': 'Kalamazoo', 'state': 'Michigan', 'enrollment': 19038, 'conference': 'MAC'},
    'Wisconsin': {'nickname': 'Badgers', 'city': 'Madison', 'state': 'Wisconsin', 'enrollment': 47932, 'conference': 'Big Ten'},
    'Wyoming': {'nickname': 'Cowboys', 'city': 'Laramie', 'state': 'Wyoming', 'enrollment': 11479, 'conference': 'Mountain West'},
}
